// Phase 87 (ADR 0063): builds the app's database from supabase/migrations/
// alone, in PGlite (PostgreSQL 17 compiled to WebAssembly, in process), so a
// migration can be replayed from empty without Docker or a Supabase project.
// supabase/replay/prelude.sql stands in for what the Supabase platform
// provides; supabase/catalog.sql lists what the result is made of.
//
// Used by scripts/schema-drift.mjs and unit/migration-replay.test.ts.
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { uuid_ossp } from '@electric-sql/pglite/contrib/uuid_ossp';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export function readRepoFile(...parts) {
  return readFileSync(join(ROOT, ...parts), 'utf8');
}

/** The migration files in the order they apply: by file name. */
export function migrationFiles() {
  return readdirSync(join(ROOT, 'supabase', 'migrations'))
    .filter(file => file.endsWith('.sql'))
    .sort();
}

/**
 * The name a file is recorded under in supabase_migrations.schema_migrations:
 * the file name without its date and extension. The live history's versions
 * are timestamps that do not match the files' date prefixes, so the history
 * is matched by name.
 */
export function migrationName(file) {
  return file.replace(/^\d+_/, '').replace(/\.sql$/, '');
}

/** An empty database with the Supabase stand-in applied. */
export async function createDatabase() {
  const db = await PGlite.create({ extensions: { uuid_ossp } });
  await db.exec(readRepoFile('supabase', 'replay', 'prelude.sql'));
  return db;
}

export async function applyMigrations(db, files = migrationFiles()) {
  for (const file of files) {
    try {
      await db.exec(readRepoFile('supabase', 'migrations', file));
    } catch (error) {
      throw new Error(`${file}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
}

/** Every row of supabase/catalog.sql, sorted. */
export async function readCatalog(db) {
  await db.exec(readRepoFile('supabase', 'catalog.sql'));
  const { rows } = await db.query(
    'select kind, name, detail from schema_catalog order by kind, name, detail');
  return rows;
}

/**
 * A probe under supabase/tests/ with each `\ir <path>` line replaced by that
 * file, as a runner without psql pastes it (MCP's execute_sql, PGlite).
 *
 * `applied: true` runs it the way its header says to once its migrations are
 * applied: the `\ir ../migrations/...` lines are dropped (other includes, such
 * as the catalog, stay), so its assertions run against the schema as it is.
 * Re-running an old migration that re-creates a function would put back the
 * old body (Phase 88: the Phase 73 file would drop the session check).
 */
export function inlineProbe(probeFile, { applied = false } = {}) {
  const probeDir = join(ROOT, 'supabase', 'tests');
  return readFileSync(join(probeDir, probeFile), 'utf8').replace(
    /^\\ir\s+(\S+)\s*$/gm,
    (_line, path) => (applied && path.startsWith('../migrations/') ? '' : readFileSync(join(probeDir, path), 'utf8')));
}

/** A database built from every migration, with its catalog. */
export async function replayAll() {
  const db = await createDatabase();
  await applyMigrations(db);
  return { db, catalog: await readCatalog(db) };
}

/** What a database built from these migrations should hold, history included. */
export function expectedRows(catalog, files = migrationFiles()) {
  return [
    ...catalog,
    ...files.map(file => ({ kind: 'migration', name: migrationName(file), detail: '' })),
  ];
}

/**
 * One read-only query that compares `expected` with the database it runs on
 * (its catalog and supabase_migrations.schema_migrations) and returns only the
 * rows that differ, each marked "only in the repo" or "only in the database".
 */
export function buildDriftCheck(expected) {
  const json = JSON.stringify(expected);
  if (json.includes('$drift$')) throw new Error('The expected rows contain the quote tag $drift$.');
  return `-- Generated by scripts/schema-drift.mjs (ADR 0063). Read-only: run it on the
-- live project. Every row it returns is drift; none means none.

${readRepoFile('supabase', 'catalog.sql').trim()}

with expected(kind, name, detail) as (
  select x.kind, x.name, x.detail
    from jsonb_to_recordset($drift$${json}$drift$::jsonb) as x(kind text, name text, detail text)
),
actual as (
  select kind, name, detail from schema_catalog
  union all
  select 'migration', coalesce(name, version), '' from supabase_migrations.schema_migrations
)
select side, kind, name, detail from (
  select 'only in the repo' as side, * from (select * from expected except select * from actual) a
  union all
  select 'only in the database', * from (select * from actual except select * from expected) b
) drift
order by kind, name, side;
`;
}
